-- PM / Sistema Sheyla - estrutura Supabase
-- Execute este arquivo no SQL Editor de um projeto Supabase novo.

create extension if not exists pgcrypto;

create table if not exists public.recibos (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity unique not null,
  data_recibo date not null default current_date,
  nome text not null,
  contato text,
  cor text,
  modelo text,
  quantidade integer not null default 1 check (quantidade > 0),
  material text,
  valor_total numeric(12,2) not null default 0 check (valor_total >= 0),
  valor_entrada numeric(12,2) not null default 0 check (valor_entrada >= 0),
  valor_restante numeric(12,2) generated always as (greatest(valor_total - valor_entrada, 0)) stored,
  tipo_pagamento text,
  dia_prova date,
  hora_prova time,
  data_entrega date,
  hora_entrega time,
  superior boolean not null default false,
  inferior boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint recibos_entrada_limite check (valor_entrada <= valor_total)
);

create table if not exists public.agendamentos (
  id uuid primary key default gen_random_uuid(),
  nome_cliente text not null,
  tipo text not null check (tipo in ('Prova', 'Entrega', 'Moldagem', 'Conserto', 'Domicílio')),
  data date not null,
  hora time not null,
  observacoes text,
  recibo_id uuid references public.recibos(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contas_pagar (
  id uuid primary key default gen_random_uuid(),
  vencimento date not null,
  fornecedor text not null,
  valor numeric(12,2) not null default 0 check (valor >= 0),
  descricao text,
  categoria text not null default 'Outros',
  forma_pagamento text,
  status text not null default 'A pagar' check (status in ('A pagar', 'Pago', 'Vencida')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contas_receber (
  id uuid primary key default gen_random_uuid(),
  vencimento date not null,
  cliente text not null,
  valor numeric(12,2) not null default 0 check (valor >= 0),
  descricao text,
  status text not null default 'A receber' check (status in ('A receber', 'Recebido', 'Em atraso')),
  recibo_id uuid unique references public.recibos(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_recibos_nome on public.recibos (lower(nome));
create index if not exists idx_recibos_dia_prova on public.recibos (dia_prova);
create index if not exists idx_recibos_data_entrega on public.recibos (data_entrega);
create index if not exists idx_agendamentos_data on public.agendamentos (data);
create index if not exists idx_contas_pagar_vencimento on public.contas_pagar (vencimento);
create index if not exists idx_contas_receber_vencimento on public.contas_receber (vencimento);

create or replace function public.set_updated_at()
returns trigger language plpgsql security invoker set search_path = public as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.sync_conta_receber_from_recibo()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.contas_receber (vencimento, cliente, valor, descricao, status, recibo_id)
  values (
    coalesce(new.data_entrega, new.data_recibo),
    new.nome,
    new.valor_restante,
    'Referente ao recibo Nº ' || new.numero,
    case when new.valor_restante = 0 then 'Recebido' else 'A receber' end,
    new.id
  )
  on conflict (recibo_id) do update set
    vencimento = excluded.vencimento,
    cliente = excluded.cliente,
    valor = excluded.valor,
    descricao = excluded.descricao,
    status = case when excluded.valor = 0 then 'Recebido' else public.contas_receber.status end,
    updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_recibos_updated_at on public.recibos;
create trigger set_recibos_updated_at before update on public.recibos for each row execute function public.set_updated_at();
drop trigger if exists set_agendamentos_updated_at on public.agendamentos;
create trigger set_agendamentos_updated_at before update on public.agendamentos for each row execute function public.set_updated_at();
drop trigger if exists set_contas_pagar_updated_at on public.contas_pagar;
create trigger set_contas_pagar_updated_at before update on public.contas_pagar for each row execute function public.set_updated_at();
drop trigger if exists set_contas_receber_updated_at on public.contas_receber;
create trigger set_contas_receber_updated_at before update on public.contas_receber for each row execute function public.set_updated_at();
drop trigger if exists sync_conta_receber_after_recibo on public.recibos;
create trigger sync_conta_receber_after_recibo after insert or update of nome, valor_total, valor_entrada, data_entrega, data_recibo on public.recibos for each row execute function public.sync_conta_receber_from_recibo();

alter table public.recibos enable row level security;
alter table public.agendamentos enable row level security;
alter table public.contas_pagar enable row level security;
alter table public.contas_receber enable row level security;

drop policy if exists "recibos_authenticated_all" on public.recibos;
create policy "recibos_authenticated_all" on public.recibos for all to authenticated using (true) with check (true);
drop policy if exists "agendamentos_authenticated_all" on public.agendamentos;
create policy "agendamentos_authenticated_all" on public.agendamentos for all to authenticated using (true) with check (true);
drop policy if exists "contas_pagar_authenticated_all" on public.contas_pagar;
create policy "contas_pagar_authenticated_all" on public.contas_pagar for all to authenticated using (true) with check (true);
drop policy if exists "contas_receber_authenticated_all" on public.contas_receber;
create policy "contas_receber_authenticated_all" on public.contas_receber for all to authenticated using (true) with check (true);

-- Depois de importar recibos antigos preservando a coluna numero, rode uma vez:
-- select setval(pg_get_serial_sequence('public.recibos', 'numero'), coalesce((select max(numero) from public.recibos), 0) + 1, false);
